### ISSUE TITLE
Not showing up in Package Control

### ISSUE THREAD

**Issue by rafegoldberg** [ehuss/Sublime-Wrap-Plus#55]
♡ Sublime Wrap Plus; really useful ‘lil plugin! but I was recently setting up a clean install of Sublime on a new laptop and couldn't find it in the Package Control “Install Package” panel. I ended up installing directly from the repo but I figured I'd letchya know! Anyway, keep making awesome things my man– thanks for the plugin!

**Comment by ehuss** [comment]
Hm, that's strange.  Seems to show up for me (and is still listed on [packagecontrol](https://packagecontrol.io/packages/Wrap%20Plus)).  

I would check that it isn't already installed (installed_packages), or that it isn't listed in ignored_packages, or if package control is showing any errors in the console.

**Comment by rafegoldberg** [comment]
I know; thought it was weird that it was still on the Package Control site but... yep, you called it– I'd accidentally added it to the ignore list! dumb
