### ISSUE TITLE
Appears not to work in newest version (3114)

### ISSUE THREAD

**Issue by minitauros** [ehuss/Sublime-Wrap-Plus#56]
I think it might be because the newest version of ST introduced improvements in the wrap_lines feature, but Wrap Plus now doesn't work as smooth as it used to in a previous version (I tink 3084): a lot of lines that shouldn't be included in the wrap are now being included in the wrap (PHP).

**Comment by minitauros** [comment]
And the new wrap_lines improvments are good, but I like Wrap Plus better :smile:.

**Comment by ehuss** [comment]
I don't think anything significant has changed (I'm on 3120).

Can you give an example of something that is not working as expected, and verify that the plugin is installed and running properly?

**Comment by minitauros** [comment]
An example (in PHP):

My cursor is in the first comment line (`// Objects that..`) when I press alt + q to run the `wrap_lines` command:
```
// Objects that do not have an owner may only be edited if they have not yet been saved (so if they don't have an ID yet).
if (!$user) {
	$user = UserAuth::getUser();
	if (!$user)
		return false; // Empty void is not allowed to edit an object.
}
```

This results in the following:
```
// Objects that do not have an owner may only be edited if they have not yet been saved (so if they
don't have an ID yet). if (!$user) { $user = UserAuth::getUser(); if (!$user) return false; // Empty
void is not allowed to edit an object. }
```

If I disable Wrap Plus, it results in (as expected):
```
// Objects that do not have an owner may only be edited if they have not yet been saved (so if they
// don't have an ID yet).
if (!$user) {
	$user = UserAuth::getUser();
	if (!$user)
		return false; // Empty void is not allowed to edit an object.
}
```

Although I like Wrap Plus better, as it formats my PHPDoc blocks that describe functions much prettier.

**Comment by minitauros** [comment]
I have found that this package is possibly conflicting with another package that I have installed. Will check it out.

**Comment by minitauros** [comment]
Lord almighty, I hope you didn't go through too much trouble there. It appears that another package was causing the problem. I am ashamed. Sorry for any inconvenience!

**Comment by ehuss** [comment]
No worries, glad you were able to figure it out.  :smile:   It's a common complaint with Sublime that it doesn't handle plugin conflicts well.  Hopefully they will improve that some day.
