### ISSUE TITLE
Wrapping a latex command

### ISSUE THREAD

**Issue by diego898** [ehuss/Sublime-Wrap-Plus#61]
For some reason trigger wrap plus doesnt work correctly when a line starts with a `\` latex command? In order to get it to work correctly I have to manually remove the line 

![](https://media.giphy.com/media/xUPGco96EJWvKaVyne/giphy.gif)

**Comment by ehuss** [comment]
I just pushed a commit that includes some latex fixes.  Feel free to reopen if this specific case is still a problem.  Keep in mind that latex support is somewhat of a hack, so it's not intended to support all cases.

**Comment by diego898** [comment]
Hello, thanks for the update! Just to keep this updated, I am experience very strange behavior with a custom latex environment. I have defined the following custom environment:
`\newcommand{\eq}[1]{\begin{equation*}\begin{aligned}#1\end{aligned}\end{equation*}}`

When I use it and try to wrap, I get the following behavior:

![](https://media.giphy.com/media/3oKIPCi8NjuvYGWnn2/giphy.gif)
