### ISSUE TITLE
Do not indent a year as a numbered list

### ISSUE THREAD

**Issue by allenz** [ehuss/Sublime-Wrap-Plus#68]
Sample input (wrap_width=80):

    In this example we describe some fascinating events which first occurred in
    2004. We're just mentioning 2004 in a sentence, so the rest of the paragraph
    should not be indented.

Output after wrapping lines:

    In this example we describe some fascinating events which first occurred in
    2004. We're just mentioning 2004 in a sentence, so the rest of the paragraph
          should not be indented.

Expected output:

    In this example we describe some fascinating events which first occurred in
    2004. We're just mentioning 2004 in a sentence, so the rest of the paragraph
    should not be indented.

**Comment by ehuss** [comment]
Fixed in c43273bb9dce1b2f98661b1ce8174990138fb499.
